### ISSUE TITLE
@page pseudo classes don't work

### ISSUE THREAD

**Issue by eriktelepovsky** [nigma/django-easy-pdf#13]
Pseudo classes for @page don't work.

``` python
{% block extra_style %}
    <style type="text/css">
        @page {
            color: black;
        }
        @page :first {
            color:red;
        }
    </style>
{% endblock %}
```

It raises TypeError:

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' at xhtml2pdf/w3c/cssParser.py in _parseAtPage, line 726
```

Any ideas for workaround?

**Comment by vyscond** [comment]
The only way i can see is to implement this selector over the xhtml2pdf library.

**Comment by peterfarrell** [comment]
This is not an Django-Easy-PDF issue. Please file a ticket at the xhtml2pdf project:

https://github.com/chrisglass/xhtml2pdf
