### ISSUE TITLE
Not running on Windows

### ISSUE THREAD

**Issue by normic** [nigma/django-easy-pdf#15]
I just tried to get easy_pdf to run.
With the smallest example it just happens nothing...

I tried a combination on Win7 (my devmachine), Python 2.7 in a virtualenv, Django 1.6.8 and reportlab 2.7.

Any ideas?

**Comment by vyscond** [comment]
You need to provide more information like the log of errors (if exists). You project's settings and the output for ```pip freeze``` so we can try figure out whats wrong! :)
