### ISSUE TITLE
How to add images in pdf ?

### ISSUE THREAD

**Issue by rajasimon** [nigma/django-easy-pdf#16]
```
from easy_pdf.rendering import render_to_pdf_response

def performance_pdf(request):
    data = {}
    return render_to_pdf_response(request, 'report/report-base.html', data)
```

I want this image include in generated pdf but below method not working.

```
<!DOCTYPE html>
<html>
<head>
    <title>{{ title|default:"" }}</title>
        <style type="text/css">
            body {
                background: white url("https://www.htgmanager.org/common/images/html_background.jpg") no-repeat right bottom;
            }
        </style>
</head>
<body>
</body>
</html>
```

**Comment by vyscond** [comment]
As you can read on [#4](https://github.com/nigma/django-easy-pdf/issues/4) @nigma explain that is only possible to get images on the PDF with they'ra hosted as static content.
As far as i can tell the way you want to load images (other content) will not work because the template never reaches the browser itself, it goes straight to the rendering functions on xhtml2pdf. To get this way working i think we need to develop a "middleware" where it download the files com link and set automatica as a static content. On the case of images a middleware to download and convert them into base64 string that will be great.

**Comment by slamus** [comment]
I found a workaround by using templatetags filters
In *myapp/pdf_filters.py*:
```python
from django import template
import urllib, cStringIO, base64

register = template.Library()

@register.filter
def get64(url):
    """
    Method returning base64 image data instead of URL
    """
    if url.startswith("http"):
        image = cStringIO.StringIO(urllib.urlopen(url).read())
        return 'data:image/jpg;base64,' + base64.b64encode(image.read())

    return url
```
In *pdf_template.html*:
```html
{% load pdf_filters %}
<img src="{{ ressource.image.url | get64 }}"/>
```

Hope it helps :)

**Comment by MALANGBEIJING** [comment]
Hi Elie,
I got error below, please help,

'pdf_filters' is not a valid tag library: Template library pdf_filters not found, tried django.templatetags.pdf_filters,django_admin_bootstrapped.templatetags.pdf_filters,django.contrib.admin.templatetags.pdf_filters,django.contrib.staticfiles.templatetags.pdf_filters

**Comment by slamus** [comment]
Hi,

You're right, the path is wrong in my example !
It must be in *myapp/templatetags/pdf_filter.py*
Don't forget to put an *_init_.py* file in your in the folder.
I'm editing my answer right now.

Keep me updated

**Comment by gungorbudak** [comment]
Dear @slamus 

I tried to use your solution to embed SVG images but it didn't work. I changed `image/png` to `image/svg+xml` but still images don't appear. Is there anyway to embed such images?

**Comment by slamus** [comment]
Hi @gungorbudak 

No idea about svg images... Maybe you can add a python package that convert svg to png ?
After a quick google search it looks like it's possible: http://stackoverflow.com/questions/6589358/convert-svg-to-png-in-python

Good luck

**Comment by gungorbudak** [comment]
@slamus 

Thanks a lot! I didn't use it but a much simpler way (SVG to PNG to embed) given here: https://gist.github.com/zgohr/3399170

**Comment by gungorbudak** [comment]
@slamus 

Now, I want to define `@font-face` to solve Turkish characters issue in my PDF but I have a remote file in Amazon S3. I'm trying the very same method here like following:

```
@register.filter
def get64(url):
    """
    Method returning base64 image data instead of URL
    """
    if url.startswith('http'):
        source = cStringIO.StringIO(urllib.urlopen(url).read()).read()
        if url.endswith('.svg'):
            binary = svg2png(source)
            return 'data:image/png;base64,' + base64.b64encode(binary)
        if url.endswith('.ttf'):
            return 'data:application/x-font-ttf;base64,' + base64.b64encode(source)
        return 'data:image/jpg;base64,' + base64.b64encode(source)
    return url
```

If I have a .ttf URL, I'm encoding it base64 and return to use it like:

```
        @font-face {
            font-family: Arial;
            src: url({{ font_src|get64 }}) format('truetype');
        }
```

But it doesn't work. Did you work with such files before? How can I solve this issue?

**Comment by juliohurtado** [comment]
I used that method. In the console I can see how the image is found but not appear in my pdf file. Someone who can help me?

I use easy_pdf.rendering.render_to_pdf_response()

**Comment by caligoig** [comment]
I am having the same issue
Cant add background (watermark) image on my pdf, any help is highly appreciated
thanks

**Comment by Nandhitha** [comment]
I had the image in project static folder. Encode the image from view and send as context data to template.

In the **views.py**,
with open("path to image", "rb") as image_file:
            encoded_string = base64.b64encode(image_file.read())

return super(..., self).get_context_data(
            image=encoded_string,
        )
send encoded_string in the the context dictionary

In **template**,
<img src="data:image/png;base64,{{ image }}"/>

**Comment by iangenius** [comment]
Has anyone found a solution to this?

**Comment by nigma** [comment]
In the develop branch I'm working on replacing the `xhtml2pdf` backend with `WeasyPrint`.
`WeasyPrint` can load images from local `file://` or remote `http/https` urls without additional workarounds.

If you want you can try this version and provide feedback under #34.

**Comment by J88G** [comment]
I still can't use any image. Someone can help ? 
`<img src="{{ ressource | get64 }}"/>`

it doesn't display anything

**Comment by MALANGBEIJING** [comment]
please try to use absolute image file path first, make sure the file path could be download with http://ip/static/whatever.jpg <http://ip/static/whatever.jpg>, something like this,

**Comment by J88G** [comment]
OK it works for some images. For images I have in my server (Need authorization to see it) how can I get them ? 
Can someone help me ?

**Comment by dhamaniasad** [comment]
I tried everything but couldn't get it to work with the master branch. The WeasyPrint branch works, but there's a minor hiccup I'm facing. 

Here's my code: https://gist.github.com/dhamaniasad/00915df1734188dd75df0b3b2052f28a

But I end up with whitespace around my main page content. (https://puu.sh/wcJ5o/0d1643fdaa.png) 

@nigma Any ideas? Am I doing something wrong? 

Edit: Fixed this. For anyone who faces this problem in the future:
```css
@page {
    margin: 0;
}
```
fixes it, as according to the CSS spec, margin properties on @page default to about 2cm.

**Comment by mord4z** [comment]
I'm using images with these codes:
In header as a background image:
```Python
@top-left {
                content: " ";
                width: 100%;
                height: 100%;
                background: url('http://{{ request.get_host }}{% static 'img/logo.png' %}') no-repeat;
                background-position: 0 20px;
               background-size: 25%;
            }
```
In header as content:
```Python
@top-center{
                width: 40%;
                height: 100%;
                content: url('http://{{ request.get_host }}{% static 'img/logo_texto_small.png' %}') "{{ title }}";
                font-family: "Helvetica", "sans-serif";
                font-size: 13pt;
            }
```
I can put images in main content in the same way:
```Python
<img src="http://{{ request.get_host }}{% static 'img/logo.png' %}" />
```

**Comment by rajasimon** [comment]
It's good thread and closing this because it's old...

**Comment by maheshnature** [comment]
i have converted html code to pdf using python. but i am not able to read the src images (https://www.meru.in/assets/mailer/bookingRefIcon.png)  i don't have a file from url i need to convert . i have more than 5 url in my code how to convert ?

**Comment by abdulnazurudeen** [comment]
for python3 , Django 3.1.7, 
on project/app/views.py
```
from django.templatetags.static import static
.
.
logourl = static('/images/logo.png')
url = request.build_absolute_uri(logourl)
```
pass above url via context

on project/app/templatetags/pdf_filters.py
```@register.filter
def to_base64(url):
    reqcontent = requests.get(url).content
    base64str = base64.b64encode(reqcontent).decode('utf-8')
    return "data:image/png;base64, " + str(base64str)
```
pdf.html
```
{% load pdf_filters %}
<img src="{{ logo | to_base64 }}" class="logo" width="200px" height="200px" alt="Logo"/>
```
