### ISSUE TITLE
Save PDF file to disk.

### ISSUE THREAD

**Issue by ajkumark** [nigma/django-easy-pdf#18]
Is there a way to save PDF to server rather than just rendering it in browser?

**Comment by vyscond** [comment]
On the [usage](https://github.com/chrisglass/xhtml2pdf/blob/master/doc/usage.rst#using-xhtml2pdf-in-django) file over the xhtml2pdf project it's posted a very tiny snippet of how can we generate a pdf for a HTTP response. Save a pdf to local folder is an part of the process. Simple and straight forward.

After reading the above snipppet it will be clear to you that this [api call](http://django-easy-pdf.readthedocs.org/en/latest/api.html#module-easy_pdf.rendering) is an equivalent. It return pure bytes. You know the drill now.

**Comment by nigma** [comment]
For reference:

```python
content = render_to_pdf(template_name, context)
```

See http://django-easy-pdf.readthedocs.io/en/latest/api.html#module-easy_pdf.rendering

**Comment by J88G** [comment]
Can someone help me, how to save it on server? 
Thanks

**Comment by ghost** [comment]
@J88G Quite sure the code snippet posted from @nigma produces an byte string. You write it to a file object as usual and save on the disk, or even pass this to a Django file field :)
