### ISSUE TITLE
string argument expected, got 'bytes'

### ISSUE THREAD

**Issue by lckyn** [nigma/django-easy-pdf#26]
Hey there,
I used that following code but i got "string argument expected, got 'bytes'".

``` python
from easy_pdf.views import PDFTemplateView

class ShowPDF(PDFTemplateView):
    template_name = "pdf.html"
```

**Comment by meako689** [comment]
Seems that you've tried to do it in python 3. this library doesn't support it.

**Comment by evansbestmann** [comment]
not supported in python3
