### ISSUE TITLE
how to show the utf-8

### ISSUE THREAD

**Issue by freetest** [nigma/django-easy-pdf#30]
class HelloPDFView(PDFTemplateView):

```
def get_context_data(self, **kwargs):
    vul_info = vul_content.objects.filter(id=112)

    return super(HelloPDFView,self).get_context_data(
        pagesize="A4",
        title="Hi-there!",
        vul_info = vul_info,
        encoding =u"utf-8",
        **kwargs
    )
template_name = "vul_pdf.html"
```

![lm](https://cloud.githubusercontent.com/assets/5380255/15067187/2a50a80e-13a1-11e6-8e3f-93a896b254f0.png)

i use the encoding=u"utf-8"

**Comment by ptrojanowski** [comment]
@freetest Do you fixed it?

**Comment by freetest** [comment]
@ptrojanowski  no,  but  i use pisa from xhtml2pdf is ok

**Comment by mlukasz7** [comment]
@ptrojanowski So how is answer? What is need in code to show utf8 characters?

**Comment by regolith** [comment]
Based on the xhtml2pdf utf-8 [sample](https://github.com/xhtml2pdf/xhtml2pdf/tree/master/tests/samples), I was able to get CJK characters to display using a `@font-face` declaration pointing at the sample `CODE2000.TTF` font.

Disliking that font's styling of latin characters, I looked for another, and the best I could find on my Mac was "Arial Unicode.ttf" (Arial Unicode MS). Somehow, even though many other fonts looked ok when viewed in Firefox's PDF viewer, they still showed as tofu in Mac Preview and Acrobat Reader. Seems like you also lose the ability to have bold weight text unless you have another .ttf for bold.

```css
@font-face {
    font-family: MyFont;
    src: url("/Library/Fonts/Arial Unicode.ttf");
}
body {
    font-family: MyFont;
}
```

I don't know if this is the best way to do it, but it's what I've found...

**Comment by chuda** [comment]
Hey, guys just wanted to share with you all, that just adding correct content type did worked for me.
In your template add this style
```html
{% block extra_style %}
   <meta http-equiv="content-type" content="text/html; charset=utf-8"> 
{% endblock %}
```

**Comment by xicopetry** [comment]
This is something that could go in the docs @chuda .

Simple and clean solution! Thanks!
