### ISSUE TITLE
ImportError: cannot import name inputstream

### ISSUE THREAD

**Issue by abhibalani** [nigma/django-easy-pdf#31]
Unable to use it getting the following error:
```

 File "C:\Python27\lib\site-packages\xhtml2pdf\parser.py", line 17, in <module>
    from html5lib import treebuilders, inputstream
ImportError: cannot import name inputstream
```

This is the same error I was getting when using xhtml2pdf.

**Comment by Valumior** [comment]
There is a fix:
https://github.com/xhtml2pdf/xhtml2pdf/issues/318

xhtml2pdf has a broken requirement.

**Comment by abhibalani** [comment]
THANKS A TON.
