### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by ThunderTrent** [nigma/django-easy-pdf#36]
My Class / View looks like this:

```
class letterView(PDFTemplateView):

    def get_context_data(self, **kwargs):
        letterID = self.kwargs['letterID']
        object = get_object_or_404(djangoLetters, id=letterID)
        return super(letterView, self).get_context_data(object=object, **kwargs)

    def get_template_names(self):
        letterID = self.kwargs['letterID']
        letterType = djangoLetters.objects.get(pk=letterID).letterType
        template_name = str(letterType.letterBackgroundBase).strip()
        # template_name = str("letter.html")
        return [template_name]
```

Anyone know where I can specify to never cache the pdf on return? I don't see it in the documentation and can't do it on the get_context_data/get_template_names views.

@never_cache declaration was what I was going to use.

**Comment by nigma** [comment]
The [never_cache(view_func)](https://docs.djangoproject.com/en/1.11/topics/http/decorators/#django.views.decorators.cache.never_cache) takes a view function as parameter so I think the easies is to apply it like this:

```python
letter_view = never_cache(LetterView.as_view())

urlpatterns = [
    url(r'^pdf-page$', letter_view),
]
```
