### ISSUE TITLE
Problem with Django 1.11 "context must be a dict rather than RequestContext"

### ISSUE THREAD

**Issue by DARKDEYMON** [nigma/django-easy-pdf#37]
the problem is with the context in rendering file in line 138 

content = loader.render_to_string(template, context)

this gives me a error "context must be a dict rather than RequestContext" I solve this with this line of code but I think it's not the best way, check this please

content = loader.render_to_string(template, context.dicts[1])

**Comment by nigma** [comment]
That should be resolved in the 0.1.1 and 0.2.0-dev1 releases published today (https://github.com/nigma/django-easy-pdf/releases).
