### ISSUE TITLE
get_context_data() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by sbboakye** [nigma/django-easy-pdf#39]
Please how do I fix this

`class GeneratePdf(PDFTemplateView):
    template_name = 'pdf/cv1.html'
    download_filename = 'cv.pdf'

    def get_context_data(self, request, **kwargs):
        profile = get_object_or_404(Profile, id=self.request.user.id)
        skill = get_object_or_404(Skill, id=self.request.user.id)
        education = Education.objects.all()
        experience = Experience.objects.all()
        return super(GeneratePdf, self).get_context_data(pagesize='A4',
                                                         profile=profile,
                                                         skill=skill,
                                                         education=education,
                                                         experience=experience)`

**Comment by sbboakye** [comment]
I get it now

**Comment by michael-niemand** [comment]
RIP all those people that would have loved an answer, too

**Comment by HT-Moh** [comment]
How did you solve the problem?
