### ISSUE TITLE
AttributeError at /invoice/ - 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by tsurantino** [nigma/django-easy-pdf#4]
Hi,

I am trying to render the example template (invoice page) and receive the following error:
http://dpaste.com/1782321/

My template:

base.html - http://dpaste.com/1782328/
invoice.html - http://dpaste.com/1782324/
views.py - http://dpaste.com/1782332/
urls.py - http://dpaste.com/1782334/

**Comment by Swapnil98** [comment]
Hello, I am having an issue with getting images on the pdf. When I put an image tag with src pointing to my image, I am getting the same error.

settings.py:

```
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'..', 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'), # We do this so that django's collectstatic copies or our bundles to the STATIC_ROOT or syncs them to whatever storage we use.
) 
```
My settings.py is here:
`RootFolder/app/mainapp/settings.py`

And my image file is here:
`RootFolder/mainapp/assets/images/img1.png`

In my html template I have put the img tag like this:
`<img src="static/images/img1.png.jpg" />`

I have also tried using `{% load staticfiles %}` and changed the img tag as 
`<img src="{% static "images/img1.jpg" %}" />`. But it doesn't work either.

When I check the sources tab, localhost doesn't show a static folder either. This is happening only in this page. Other than this page, I get the static folder in all the other pages.

@nigma Can you please look into it and help me

**Comment by Swapnil98** [comment]
Okay, I found a fix but its not what I desire.

I had to make a static folder in the RootFolder and pu the image inside that folder. But it would be really convenient if this problem could be solved. Is there a way to avoid what I have done?
