### ISSUE TITLE
NameError: name 'render_to_content_file' is not defined

### ISSUE THREAD

**Issue by neerajgupta2407** [nigma/django-easy-pdf#46]
I can;t see the function 'render_to_content_file' , which is described here.
https://django-easy-pdf.readthedocs.io/en/v0.2.0-dev1/api.html#easy_pdf.rendering.render_to_content_file

I need to generate the PDF from html.
Is there any other way usein easy_pdf? 
TIA

**Comment by nigma** [comment]
Make sure you have the 0.2.0-dev1 version installed. See https://github.com/nigma/django-easy-pdf/releases/tag/v0.2.0-dev1.
