### ISSUE TITLE
How to import image with PDFTemplateResponseMixin

### ISSUE THREAD

**Issue by aureliendebord** [nigma/django-easy-pdf#48]
Hello,

The image does not load on my PDF.
Here is the **views.py**
```
from easy_pdf.views import PDFTemplateResponseMixin
from django.conf import settings

class PostPDFDetailView(PDFTemplateResponseMixin,DetailView):
    model = models.Post
    template_name = 'post/post_pdf.html'

    base_url = 'file://' + settings.STATIC_ROOT

    def get_context_data(self, **kwargs):
        return super(PostPDFDetailView, self).get_context_data(
            pagesize='A4',
            **kwargs
        )
```

Here the PDF template, **post_pdf.html** 
```
{% load static from staticfiles %}
{% load simulation_extras %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="container">
        <img src="file:///STATIC_ROOT/images/logo-home.png"/>
    </div>
</body>
</html>
```

**Comment by nigma** [comment]
I think you need to replace the `STATIC_ROOT` in the template with an actual absolute location of the image or even better use url relative to the `base_url` set in the view.

**Comment by aureliendebord** [comment]
No image despite all the paths seem good:

**views.py**
```

class PostPDFDetailView(PDFTemplateResponseMixin,DetailView):
    model = models.Post
    template_name = 'post/post_pdf.html'

    base_url = 'file://{}/'.format(settings.STATIC_ROOT)
```

**post_pdf.html**
`<img src="images/logo-home.png" />`

**settings.py**
```
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
```

**EDIT:** it works on heroku but not in local

**Comment by brayan15** [comment]
Try running `python manage.py collectstatic`

**Comment by brayan15** [comment]
on my case I can render images on local, but on server I can't render images, maybe some suggestions?

**Comment by djcroissant** [comment]
I was having a similar issue getting my stylesheets to load.. I got it to work by adding an additional "/" to the base_url path:
In views.py:
`base_url = 'file://' + settings.STATIC_ROOT + '/'`

Then dropping the backslash so the relative url in the template looks like this:
`<link rel="stylesheet" type="text/css" href="css/pdfgen/style.css" />`
